#!/usr/bin/env sh

repo_root=$(git rev-parse --show-toplevel)

if [ "$AUTOHOOK_STAGED_FILES" = '' ]; then
  python_files=$(find "$repo_root/py262" "$repo_root/tests" -type f -name '*.py')
else
  python_files=$AUTOHOOK_STAGED_FILES
fi

pylama $python_files
result=$?
if [ "$result" -ne 0 ]; then
  exit $result
fi

mypy "$repo_root/py262"
result=$?
if [ "$result" -ne 0 ]; then
  exit $result
fi
