#!/usr/bin/env sh

# lint with pylint, then mypy
printf '\nrunning pylint...\n\n'
pylint py262
pylint_result=$?

if [ "$pylint_result" -ne 0 ]; then
  printf 'running mypy...\n\n'
  mypy py262
  mypy_result=$?
else
  exit $pylint_result
fi

exit $mypy_result
