#!/usr/bin/env sh

repo_root=$(git rev-parse --show-toplevel)

if [ "$AUTOHOOK_STAGED_FILES" = '' ]; then
    python_files=$(find "$repo_root/py262" -type f -name '*.py')
else
    python_files=$AUTOHOOK_STAGED_FILES
fi

isort --check -rc $python_files
result=$?

if [ "$result" -ne 0 ]; then
    isort $python_files
    exit $result
fi
