#!/usr/bin/env sh

repo_root=$(git rev-parse --show-toplevel)

python_files=$(find "$repo_root/py262" -type f -name '*.py')

isort --check $python_files
result=$?

if [ "$?" -ne 0 ]; then
    isort $python_files
    exit $result
fi
